# Generated by Django 4.1.7 on 2023-02-23 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile", options={"verbose_name": "Profile"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="governrate",
            field=models.CharField(
                blank=True,
                choices=[("1", "cairo"), ("2", "mansoura"), ("3", "alex")],
                max_length=20,
                null=True,
                verbose_name="Governrate",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="universty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "cairo universty"),
                    ("2", "mansoura universty"),
                    ("3", "ECU"),
                ],
                max_length=20,
                null=True,
                verbose_name="Universty",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User name",
            ),
        ),
    ]
